[package]
name = "onyums"
version = "0.1.23"
edition = "2021"
license = "MIT"
repository = "https://github.com/basic-automation/onyums"
readme = "README.md"
description = "An Onion-service server using axum."
keywords = ["tor", "http", "request", "server", "SOCKS"]
categories = ["network-programming", "web-programming::http-client"]

[dependencies]
anyhow = { workspace = true }
hyper = { workspace = true, features = ["full"] }
hyper-util = { workspace = true, features = ["full"] }
futures = { workspace = true }
arti-client = { workspace = true, features = ["full", "static"] }
tor-cell = { workspace = true, features = ["full"] }
tor-hsservice = { workspace = true, features = ["full"] }
tor-proto = { workspace = true, features = ["full"] }
tor-rtcompat = { workspace = true, features = ["full"] }
tor-cert = { workspace = true }
tokio = { workspace = true, features = ["full"] }
axum = { workspace = true, features = ["http2"] }
tower-service = { workspace = true }
tracing = { workspace = true }
rcgen = { workspace = true }
tokio-rustls = { workspace = true, default-features = false, features = ["logging", "tls12", "ring"] }

[dev-dependencies]
tracing-subscriber = { workspace = true }