unstable_features = true
reorder_imports = true
imports_granularity = "Crate"
max_width = 1000
tab_spaces = 4
hard_tabs = true
imports_layout = "Horizontal"
reorder_impl_items = true
group_imports = "StdExternalCrate"
